
export const GET_DATA_REQ = "GET_DATA_REQ";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILED = "GET_DATA_FAILED";

export const UPDATE_FDC_REQ = "UPDATE_FDC_REQ";
export const UPDATE_FDC_SUCCESS = "UPDATE_FDC_SUCCESS";
export const UPDATE_FDC_FAILED = "UPDATE_FDC_FAILED";


